# -*- coding: utf-8 -*-
"""Bigdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ro-F8S_uO2AMR85oFAc2_ZBv6OAfYNJx

## 🌍 BigData Clean & Transform – UK Macroeconomy

BigData Clean & Transform é um projeto desenvolvido com Apache Spark em Python (PySpark), voltado para o tratamento, limpeza e transformação de dados econômicos macroestruturais do Reino Unido. Ele exemplifica boas práticas em engenharia de dados para projetos que exigem processamento distribuído, manipulação de datasets grandes e automação de rotinas analíticas em ambiente cloud.

| 💡 Recurso                                   | 🧩 Descrição                                                                                                         |
| -------------------------------------------- | -------------------------------------------------------------------------------------------------------------------- |
| **Setup automático do Spark 3.0**            | Inclui configuração do ambiente Spark/Hadoop e dependências em notebooks Colab para rápida execução em nuvem.        |
| **Ingestão de dados econômicos**             | Carregamento direto de dados CSV macroeconômicos (população e taxa de desemprego) via `wget` remoto.                 |
| **Data Wrangling com PySpark**               | Processos robustos de renomeação, filtragem semântica, tratamento de valores nulos e deduplicação.                   |
| **Filtragem semântica com `left_anti` join** | Remove registros descritivos não analíticos, como linhas com “Units”, garantindo dados puros para análise.           |
| **Engenharia de variáveis temporais**        | Criação de coluna `century` a partir do ano, permitindo agrupamentos históricos de maneira eficiente.                |
| **Paralelização e gravação particionada**    | Dados são reparticionados por século e exportados em CSV, prontos para análises posteriores ou ingestão em sistemas. |
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# 
# !wget -q https://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz
# 
# !tar xf spark-3.0.0-bin-hadoop2.7.tgz && rm spark-3.0.0-bin-hadoop2.7.tgz

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# 
# !apt-get remove openjdk*
# !apt-get update --fix-missing
# !apt-get install openjdk-8-jdk-headless -qq > /dev/null

!pip install -q pyspark==3.0.0

!pip install py4j

import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.0.0-bin-hadoop2.7"

!pip install -q findspark==1.4.2

import findspark

findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").appName("pyspark-notebook").getOrCreate()

# Comando para baixar o arquivo CSV
!wget -q "https://raw.githubusercontent.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker/master/build/workspace/data/uk-macroeconomic-data.csv" -O "uk-macroeconomic-data.csv"

data = spark.read.csv(path="uk-macroeconomic-data.csv", sep=",", header=True)

data.show()

data.printSchema()

"""- Data Wrangling"""

data.count()

data.columns

len(data.columns)

data = data.select([ "Description", "Population (GB+NI)", "Unemployment rate" ])

data = data.withColumnRenamed("Description", 'year').withColumnRenamed("Population (GB+NI)", "population").withColumnRenamed("Unemployment rate", "unemployment_rate")

data.show(n=10)

data_description = data.filter(data['year'] == 'Units')

data_description.show(n=10)

(data.count(), len(data.columns))

(data_description.count(), len(data_description.columns))

from pyspark.sql.functions import broadcast

data = data.join( other=broadcast(data_description) , on=['year'], how='left_anti' )

data.show(n=10)

data = data.dropna()

data.show(n=10)

data = data.withColumn( 'century', 1 + (data['year']/100).cast('int') )

data.select(['century', 'year']). groupBy('century').agg({'year': 'count'}).show()

timing = data.select(['century', 'year']).groupBy('century').agg({'year': 'count'}).collect()

timing

timing[0].asDict()

data.repartition('century').write.csv( path="uk-macroeconomic-data-clean", sep=",", header=True, mode="overwrite" )

"""## Diferenciais e Valor Agregado

✅ Escalabilidade: Pronto para processar milhões de linhas com o poder do Spark.

✅ Integração com pipelines automatizados: Ideal para ser acoplado a workflows de ETL em sistemas cloud-native.

✅ Foco em dados limpos e confiáveis: Aplicação clara de boas práticas em data cleaning e pré-processamento.

✅ Ambiente portátil e replicável: Projetado para execução em ambientes como Google Colab ou clusters Spark.
"""